[versions]
# Project
androidGradlePlugin = "8.13.0"
playservicesGradlePlugin = "4.4.4"
firebaseCrashlyticsGradlePlugin = "3.0.6"

# AndroidX
androidxCore = "1.17.0"
androidxComposeBom = "2025.11.00"
androidxStartUp = "1.2.0"
androidxLifecycle = "2.9.4"
androidxHilt = "1.3.0"
androidxCoreSplashScreen = "1.2.0"
androidxActivity = "1.11.0"
androidxNavigation = "2.9.6"
androidxDataStore = "1.1.7"
androidxRoom = "2.8.3"
androidxAppcompat = "1.7.1"
androidxPaging = "3.3.6"

# Android
androidPlayServicesLocation = "21.3.0"

# Kotlin
kotlin = "2.2.20"
kotlinxCoroutines = "1.10.2"
kotlinxSerializationJson = "1.9.0"
ksp = "2.2.20-2.0.4"

# Firebase
firebaseBom = "34.5.0"

# hilt
hilt = "2.57.2"

# Coil
coil = "3.3.0"

# coreDseugar
androidDesugarJdkLibs = "2.1.5"

# ETC
retrofit = "3.0.0"
okhttp = "5.3.0"
lottie = "6.7.1"
timber = "5.0.1"
leakCanary = "2.14"
compressor = "3.0.1"
calendarCompose = "2.9.0"
composeStableMarker = "1.0.7"
kakaoCore = "2.22.0"
zoomable = "2.8.2"
naverMapCompose = "1.9.0"
naverMapLocation = "21.0.2"
tedClusteringNaver = "1.0.2"
ksoup = "0.2.5"
material = "1.13.0"

[libraries]
# AndroidX
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-startup = { group = "androidx.startup", name = "startup-runtime", version.ref = "androidxStartUp" }
androidx-dataStore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-core-splashScreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashScreen" }

# AndroidX Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }

# AndroidX Activity Compose
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }

# AndroidX Lifecycle
androidx-lifecycle-runtime-compose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-savedState = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-savedstate", version.ref = "androidxLifecycle" }

# AndroidX Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-coroutine = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-paging = { group = "androidx.room", name = "room-paging", version.ref = "androidxRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" } # For Kotlin use Ksp instead of annotationProcessor

# AndroidX Paging
androidx-paging-runtime = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "androidxPaging" }
androidx-paging-common = { group = "androidx.paging", name = "paging-common-ktx", version.ref = "androidxPaging" }
androidx-paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "androidxPaging" }

# AndroidX Navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }

# AndroidX Hilt
androidx-hilt-common = { group = "androidx.hilt", name = "hilt-common", version.ref = "androidxHilt" }
androidx-hilt-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "androidxHilt" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHilt" }

# Android
android-play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "androidPlayServicesLocation" }

# Hilt
hilt-core = { group = "com.google.dagger", name = "hilt-core", version.ref = "hilt" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }

# Android ETC
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" } # coreLibraryDesugaring

# kotlin
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
kotlin-compose-compiler-extension = { group = "org.jetbrains.kotlin", name = "compose-compiler-gradle-plugin", version.ref = "kotlin" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" } # For platform
firebase-messageing= { group = "com.google.firebase", name = "firebase-messaging" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }

# Coil
coil-kt-network = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil" }

# ETC
ksoup = { module = "com.fleeksoft.ksoup:ksoup", version.ref = "ksoup" }
ksoup-network = { module = "com.fleeksoft.ksoup:ksoup-network", version.ref = "ksoup" }
retrofit-core = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "retrofit" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }

timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }
lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottie" }
compose-stable-marker = { group = "com.github.skydoves", name = "compose-stable-marker", version.ref = "composeStableMarker" }
calendar-compose = { group = "com.kizitonwose.calendar", name = "compose", version.ref = "calendarCompose" }

naver-map-compose = { group = "io.github.fornewid", name = "naver-map-compose", version.ref = "naverMapCompose" }
naver-map-location = { group = "io.github.fornewid", name = "naver-map-location", version.ref = "naverMapLocation" }
tedclustering-naver = { group = "io.github.ParkSangGwon", name = "tedclustering-naver", version.ref = "tedClusteringNaver" }

leakCanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakCanary" }
compressor = { group = "id.zelory", name = "compressor", version.ref = "compressor" }
kakao-login = { group = "com.kakao.sdk", name = "v2-user", version.ref = "kakaoCore" }
image-zoomable = { group = "net.engawapg.lib", name = "zoomable", version.ref = "zoomable" }

# Dependencies of the included build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[bundles]
androidx-room = ["androidx-room-runtime", "androidx-room-coroutine", "androidx-room-paging"]
androidx-paging = ["androidx-paging-runtime", "androidx-paging-common", "androidx-paging-compose"]
androidx-lifecycle = ["androidx-lifecycle-runtime-compose", "androidx-lifecycle-viewModel-compose", "androidx-lifecycle-savedState"]
coil = ["coil-kt-network", "coil-kt-compose", "coil-kt-svg"]
retrofit = ["retrofit-core", "retrofit-converter-kotlinx-serialization", "okhttp-logging"]
naver-map-compose = ["naver-map-compose", "naver-map-location", "tedclustering-naver", ]

[plugins]
# Android Plugin
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }

# Kotlin Plugin
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# ETC Plugin
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
playServices = { id = "com.google.gms.google-services", version.ref = "playservicesGradlePlugin" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Plugins defined by this project
moim-android-application = { id = "moim.android.application", version = "unspecified" }
moim-android-application-compose = { id = "moim.android.application.compose", version = "unspecified" }
moim-android-library = { id = "moim.android.library", version = "unspecified" }
moim-android-library-compose = { id = "moim.android.library.compose", version = "unspecified" }
moim-android-feature = { id = "moim.android.feature", version = "unspecified" }
moim-android-hilt = { id = "moim.android.hilt", version = "unspecified" }
moim-jvm-library = { id = "moim.jvm.library", version = "unspecified" }
moim-jvm-hilt = { id = "moim.jvm.hilt", version = "unspecified" }
